var urls = [
  // 'http://pennpep.upenn.edu/',
  'http://jamcater.com/',
  'http://medicalethics.med.upenn.edu/',
  'https://freshartists.org/',
  'http://scattergoodethics.org/',
  'http://www.fandm.edu/',
  'https://pikprofessors.upenn.edu/',
  'http://ihousephilly.org/',
  // 'http://global.upenn.edu/',
  'http://digsau.com/',
  'https://provost.upenn.edu/'
  // 'http://interface-studio.com': 2005,
  // 'http://press.visitphilly.com': 2007,
  // 'http://gtms.org': 2008,
  // 'http://askemap.org': 2009,
  // 'http://gilkerlin.com': 2009,
  // 'http://kimberton.org': 2009,
  // 'http://pogil.org': 2009,
  // 'http://ldi.upenn.edu/': 2010,
  // 'http://ccaha.org': 2010,
  // 'http://philly360.visitphilly.com': 2010,
  // 'http://aapss.org': 2010,
  // 'http://cgi.unc.edu': 2010,
  // 'http://cs.uarts.edu': 2010,
  // 'http://connectthecircuit.org': 2011,
  // 'http://www.rap-arcc.org/': 2011,
  // 'http://civilwarmuseumphila.org': 2011,
  // // rendering problem
  // // 'http://pasbdc.org': 2011,
  // 'http://www.apostrophenow.com/': 2011,
  // 'http://chibe.upenn.edu': 2011,
  // 'http://worldclassgreaterphila.org': 2011,
  // 'https://autismmatch.org/': 2012,
  // 'http://greatphillyschools.org': 2012,
  // 'http://tps.uarts.edu': 2012,
  // 'http://planphilly.com/': 2013,
  // 'http://thefoodtrust.org': 2013,
  // 'http://ihousephilly.org': 2013,
  // 'http://drwc.org/': 2013,
  // 'http://cuspproject.org/': 2013,
  // 'http://moore.edu': 2013,
  // 'http://punkave.com': 2013,
  // 'http://greenestreetfriends.org/': 2013,
  // 'http://www.themichaelsorg.com': 2013,
  // 'http://grayareaphilly.org': 2013,
  // 'http://papayalive.org': 2014,
  // 'http://efworld.org': 2014,
  // 'http://phillyfunguide.com': 2014,
  // 'http://ccdparks.org': 2014,
  // 'http://weathervanemusic.org': 2014,
  // 'http://carolinereesemusic.com/': 2014,
  // 'http://seventy.org': 2014,
  // 'http://junto.org': 2014,
  // 'http://bettertomorrows.org': 2014,
  // // ssl problem
  // // 'https://pikprofessors.upenn.edu': 2014,
  // 'http://pie-charts.pie-network.org': 2014,
  // 'http://www.lgarch.com': 2014,
  // 'http://ece.greatphillyschools.org/': 2014,
  // 'http://fandm.edu': 2014,
  // 'http://goodcompanygroup.org': 2014,
  // 'http://apostrophenow.org': 2014,
  // 'http://ortnercenter.org': 2015,
  // 'http://netgainchallenge.org': 2015,
  // 'http://freshartists.org': 2015,
  // 'http://www.pahumanities.org/': 2015,
  // 'http://www.digsau.com/': 2015,
  // 'http://aprweb.org': 2015,
  // 'http://new-guide.punkave.com/': 2015
];

if (typeof(module) !== 'undefined') {
  module.exports = urls;
} else {
  window.urls = urls;
}
