module.exports = [
  'http://interface-studio.com',
  'http://press.visitphilly.com',
  'http://askemap.org',
  'http://gilkerlin.com',
  'http://ldi.upenn.edu/',
  'http://gtms.org',
  'http://connectthecircuit.org',
  'http://www.rap-arcc.org/',
  'http://kimberton.org',
  'http://pogil.org',
  'http://mgza.com',
  'http://ccaha.org',
  'http://philly360.visitphilly.com',
  'http://aapss.org',
  'http://penniur.upenn.edu',
  'http://cgi.unc.edu',
  'http://civilwarmuseumphila.org',
  'http://pasbdc.org',
  'https://autismmatch.org/',
  'http://www.apostrophenow.com/',
  'http://chibe.upenn.edu',
  'http://greatphillyschools.org',
  // down?
  // 'http://cs.uarts.edu',
  // 'http://tps.uarts.edu',
  'http://worldclassgreaterphila.org',
  'http://planphilly.com/',
  'https://autismmatch.org/',
  'http://thefoodtrust.org',
  'http://ihousephilly.org',
  'http://drwc.org/',
  'http://cuspproject.org/',
  'http://moore.edu',
  'http://greenestreetfriends.org/',
  'http://www.themichaelsorg.com',
  'http://papayalive.org',
  'http://efworld.org',
  'http://grayareaphilly.org',
  'http://phillyfunguide.com',
  'http://ccdparks.org',
  'http://weathervanemusic.org',
  'http://seventy.org',
  'http://junto.org',
  'http://bettertomorrows.org',
  'http://pik.upenn.edu',
  'http://charliewasasinner.com',
  'http://pie-charts.pie-network.org',
  'http://www.lgarch.com',
  'http://ortnercenter.org',
  'http://netgainchallenge.org',
  'http://ece.greatphillyschools.org/',
  'http://fandm.edu',
  'http://goodcompanygroup.org',
  'http://new-guide.punkave.com/',
  'http://punkave.com'
];

